### ISSUE TITLE
Issue with dom notation

### ISSUE THREAD

**Issue by set-webmaster** [DataTables/SearchPanes#1]
Datatables `Scroller` extension uses the same 'S' notation in the `dom` variable to specify the extension. 

It causes conflict and doesn't load the table at all.

**Comment by set-webmaster** [comment]
Fixed with https://github.com/DataTables/SearchPanes/commit/2a1f7fa3bfd9a7060b745d9f1945809982155197

**Comment by colin0117** [comment]
Ah, yep, thanks for updating the thread - I did it too early in the morning and brain not quite awake.
