### ISSUE TITLE
Add internationalisation option for Clear All button

### ISSUE THREAD

**Issue by marceloverdijk** [DataTables/SearchPanes#13]
Currently the Clear All button test is hardcoded:
https://github.com/DataTables/SearchPanes/blob/9069540cc5d2c59acec530ff9f7eb2bb514eebb0/src/searchPanes.ts#L73

It would be nice to be able to set it via an internationalisation option.

**Comment by marceloverdijk** [comment]
While looking into creating a PR I found out I was wrong and it can be configured using `language.searchPanes.clearMessage`:

https://github.com/DataTables/SearchPanes/blob/9069540cc5d2c59acec530ff9f7eb2bb514eebb0/src/searchPanes.ts#L112

The initial hardcoded value and that is not mentioned in the docs gave me wrong impression.

I have created PR #14 to add the missing configuration option to the docs.

**Comment by SandyDatatables** [comment]
Thank you for spotting this.

I've merged the pull request and made a small change to the description you provided.

Thanks,
Sandy
