### ISSUE TITLE
Selector for Bootstrap 3 isn't specific enough

### ISSUE THREAD

**Issue by hellodaniel** [DataTables/SearchPanes#19]
`div.row` selector in `css/searchPanes.bootstrap.scss` (line 23) is way too unspecific and messes with any nested rows inside layouts where SearchPanes is CSS is included. 

I'm not sure if this is required for SP to work maybe you don't need to comma and you mean it to be nested instead? Removing it fixes the other layouts but I haven't tested the outcome within SP itself... 

https://github.com/hellodaniel/SearchPanes/commit/85a1bfcca364e33ec51ba93ca24f045f5140e2e0#diff-c46e70555fa611eed1a3871244ac188181dbcdc5caf8517064d96fd10c3f3a98

**Comment by SandyDatatables** [comment]
Hi @hellodaniel ,

Thanks for pointing this out, you're quite right. I've made a change to move the css within the SearchPanes div (see [this commit](https://github.com/DataTables/SearchPanes/commit/b922d3f9fd6bca0afdfe9063faae336ec64a7be1)).

Thanks,
Sandy
