### ISSUE TITLE
string method replaceAll doesn't exist for IE browsers

### ISSUE THREAD

**Issue by coolblades** [DataTables/SearchPanes#20]
Not sure if IE11 is supported or not.
But I am getting js error when running this extension 
it doesn't like replaceAll medhod for string at line

```
colSelect.filter = colSelect.filter.replaceAll('&amp;', '&');
```

if I were to replace it with 

```
colSelect.filter = colSelect.filter.replace(/&amp;/g, '&');
```

online example 
https://datatables.net/extensions/searchpanes/examples/initialisation/cascadePanes.html
also getting the same error with IE11

btw, great work on this, we liked the search pane very much.

**Comment by SandyDatatables** [comment]
Thanks for Spotting this and the feedback.

The commit above implements the change as you have suggested.

I'm going to close this issue now.

Thanks,
Sandy
