### ISSUE TITLE
cascade searchPanes with total and subtotal with active search

### ISSUE THREAD

**Issue by Peter83** [DataTables/SearchPanes#21]
There's a bug that happens when you have a filter (or a search) on Datatable and multiple searchPane filters, let's say 3 active.
When de-activating two of those active filters, remaining only one, the available filters and shown attribute are not calculated correctly, since the search is not applied!

live Ex:
https://datatables.net/extensions/searchpanes/examples/initialisation/viewTotalCascade.html

- Put New York inside the searcher.
- select a filter for each of the 3 pane.
- deselect 2 of previously selected filters.
- the remaining pane doesn't show filters (also total and subtotal) that are aligned with the search, they are simple all the available data.

They should be filtered as after step 1, when typing "New York" inside the searcher.

Thank you!

**Comment by SandyDatatables** [comment]
Hi @Peter83 ,

Thanks for spotting this - something isn't right there. I've raised an issue internally (DD-1769 for my reference) and will report back here when there is an update. Probably within the next week.

Thanks,
Sandy

**Comment by Peter83** [comment]
thank you so much!
great work!

**Comment by SandyDatatables** [comment]
Hi @Peter83 ,

That's a fix pushed up now. I've moved it to our test pile and will report back here once colin has had a look at it.

Thanks,
Sandy

**Comment by SandyDatatables** [comment]
Those further fixes seem to proved behaviour as expected, so I'm going to close the issue now.
