### ISSUE TITLE
Search field result included rendering html content instead of just the data

### ISSUE THREAD

**Issue by coolblades** [DataTables/SearchPanes#23]
As you can see from the image here, I typed in span and the nothing is filtered out. it is because the searching is rendering html and not just data itself.

![image](https://user-images.githubusercontent.com/7798211/105505873-75bbef80-5c97-11eb-8186-07a09e27c3f7.png)

Perhaps the columnDefs for data: 'display' should check for type of 'filter' and returning just the data.

**Comment by SandyDatatables** [comment]
Hi @coolblades ,

Thanks for pointing this out. Something isn't right there. I've raised an issue internally (DD-1843 for my reference) and will report back here when there is an update.

Thanks,
Sandy

**Comment by coolblades** [comment]
Thanks!

**Comment by SandyDatatables** [comment]
Colin has had a look now and is happy so I am going to close this now.
