### ISSUE TITLE
Feature Request: Range Slider

### ISSUE THREAD

**Issue by tacman** [DataTables/SearchPanes#28]
Instead of selecting individual ages, I'd like to see a range slider, something like rSlider.js

![image](https://user-images.githubusercontent.com/619585/224449099-ab659a42-43b1-4487-8ff9-dbc087f61902.png)

This control seems more usable:

![image](https://user-images.githubusercontent.com/619585/224448971-3610f2be-3bb5-4f9e-b03f-519c23d1de46.png)

https://www.cssscript.com/best-range-slider-replacement-libraries/

(there are many range sliders, any of them would be fine, it's just almost impossible to select from a large list of numbers).

**Comment by AllanJard** [comment]
Hi - thanks for the request. This is actually outside the scope of what I want SearchPanes to do. SearchPanes should just be concerned with lists of data which can be used to filter the table. Our _SearchBuilder_ extension is more suited for this type of data. Have a look at [this example](https://datatables.net/extensions/searchbuilder/examples/initialisation/simple.html). Although it isn't a slider, you can enter two numbers for a "between" operation when working with a number column.

**Comment by tacman** [comment]
Thanks, Allan.  I have some more comments, but I'll move them to the forums.
