### ISSUE TITLE
Performance issue when using cascadePanes and table.ajax.reload

### ISSUE THREAD

**Issue by os1r1s110** [DataTables/SearchPanes#4]
I haven't had time yet to figure out exactly where the major pain point is, but the performance decreases rapidly if using the `Searchpanes` (with cascadePanes in my case) and also reloading table data dynamically using `table.ajax.reload` ( I did report it in the forum feedback thread, but I think here might be better to track related changes to code etc...)

Effectively, when reloading table data a couple times with the `ajax.reload` method, some functions are called over 140 times (and these are not "super small" functions, such as `SearchPane.prototype._updateCommon` which does some decent job in itself.

**Comment by SandyDatatables** [comment]
Hi, thanks for spotting this.

This was indeed the case, here is a link to the [forum thread](https://datatables.net/forums/discussion/60576/searchpane-issue-with-cascade-and-ajax-reload#latest) where more discussion on this and the resolution can be found.

Thanks,
Sandy

**Comment by os1r1s110** [comment]
Yup, that's my thread on the forum ahah :) I just didn't know at that time the preferred way to report bugs ahah, thanks for closing though I had forgotten about it here.
