### ISSUE TITLE
Cannot install with npm

### ISSUE THREAD

**Issue by thrazu** [DataTables/SearchPanes#9]
Steps:
```
npm install datatables.net-searchpanes
npm install datatables.net-searchpanes-bs4
```
Added code:
```
require('datatables.net-searchpanes');
require('datatables.net-searchpanes-bs4');
```
Run:
```
npm run watch
```
Got this errors:

> ERROR  Failed to compile with 1 errors                                                                                                                          3:49:25 PM
> 
> This dependency was not found:
> 
> * datatables.net-searchPanes in ./node_modules/datatables.net-searchpanes-bs4/js/searchPanes.bootstrap4.js
> 
> To install it, you can run: npm install --save datatables.net-searchPanes

>  ERROR  Failed to compile with 1 errors                                                                                                                          3:50:52 PM
> 
> This dependency was not found:
> 
> * datatables.net-searchPanes in ./node_modules/datatables.net-searchpanes-bs4/js/searchPanes.bootstrap4.js
> 
> To install it, you can run: npm install --save datatables.net-searchPanes
>             Asset     Size   Chunks             Chunk Names
> /css/adminlte.css  0 bytes  /js/app  [emitted]  /js/app
>      /css/app.css  908 KiB  /js/app  [emitted]  /js/app
>  + 1 hidden asset
> 
> ERROR in ./node_modules/datatables.net-searchpanes-bs4/js/searchPanes.bootstrap4.js
> Module not found: Error: Can't resolve 'datatables.net-searchPanes' in '/var/www/node_modules/datatables.net-searchpanes-bs4/js'
>  @ ./node_modules/datatables.net-searchpanes-bs4/js/searchPanes.bootstrap4.js 4:8-6:10
>  @ ./resources/js/datatables.net.js
>  @ multi ./resources/js/app.js ./resources/js/datatables.net.js ./resources/js/admin-products.js ./resources/sass/app.scss ./resources/sass/adminlte.scss

It seems like that capitalized P in `datatables.net-searchPanes` is the problem.

**Comment by tuxgasy** [comment]
Hi,

I have the same bug with yarn.

**Comment by SandyDatatables** [comment]
Hi, thanks for spotting this. 

This bug was also mentioned in the [Datatables Forums](https://datatables.net/forums/discussion/60647/search-panes-wrong-package-name-included#latest) and we fixed it from there so I am going to close this issue. Take a look at [this commit](https://github.com/DataTables/SearchPanes/commit/1bf68c5e8589f8f3e727f1944dc9e14f6998018e).

**Comment by daniel-butler** [comment]
I am running into this error with searchpanes version 1.1.1 all of the datatables versions is below

```
+-- datatables.net@1.10.21
+-- datatables.net-bs4@1.10.21
+-- datatables.net-buttons@1.6.2
+-- datatables.net-buttons-bs4@1.6.2
+-- datatables.net-fixedheader@3.1.7
+-- datatables.net-fixedheader-bs4@3.1.7
+-- datatables.net-searchpanes@1.1.1
+-- datatables.net-searchpanes-bs4@1.1.1
+-- datatables.net-select@1.3.1
+-- datatables.net-select-bs4@1.3.1
```
